apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-pvc
  namespace: asset-spy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: kafka-broker-pv
  storageClassName: ""