apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker-pv
  namespace: asset-spy
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""
  hostPath:
    path: /mnt/data/kafka
