apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: asset-spy
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: external
      port: 29092
      targetPort: 29092
    - name: controller
      port: 9093
      targetPort: 9093
  type: ClusterIP
