apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: observability
data:
  jaeger.yaml: |
    apiVersion: 1
    datasources:
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686/jaeger
        isDefault: false
        jsonData:
          nodeGraph:
            enabled: true
          httpMethod: GET
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: 60s