apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: observability
data:
  jaeger.yaml: |
    apiVersion: 1
    datasources:
      - name: Jaeger
        uid: jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686/jaeger
        isDefault: true
        jsonData:
          nodeGraph:
            enabled: true
          httpMethod: GET