apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: asset-spy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@assetspy.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: assetspy123
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 100m
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-data
      volumes:
        - name: pgadmin-data
          emptyDir: {}

