apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: asset-spy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
