apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-pod-manager-binding
  namespace: asset-spy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-pod-manager
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: asset-spy
