apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: asset-spy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app.kubernetes.io/component: jenkins-controller
