apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/name: jenkins
  name: jenkins
  namespace: asset-spy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: jenkins-controller
      app.kubernetes.io/instance: jenkins
  serviceName: jenkins
  template:
    metadata:
      labels:
        app.kubernetes.io/component: jenkins-controller
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/name: jenkins
    spec:
      serviceAccountName: jenkins
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub-pull
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 90
      containers:
        - name: jenkins
          image: nastss6tx5/jenkins-controller-ci:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: JENKINS_OPTS
              value: --webroot=/var/jenkins_home/war
            - name: JENKINS_JAVA_OPTIONS
              value: "-Xms256m -Xmx1024m -XX:+UseContainerSupport"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 50000
              name: agent
              protocol: TCP
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1.5Gi"
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
        - name: dind
          image: docker:27-dind
          imagePullPolicy: IfNotPresent
          args:
            - --host=tcp://0.0.0.0:2375
            - --tls=false
            - --storage-driver=overlay2
            - --iptables=false
          env:
            - name: DOCKER_TLS_CERTDIR
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            runAsUser: 0
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: docker-run
              mountPath: /var/run
      volumes:
        - emptyDir: {}
          name: jenkins-cache
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins
        - emptyDir: {}
          name: sc-config-volume
        - emptyDir: {}
          name: tmp-
