apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      filter/ignore-noisy:
        traces:
          span:
            - 'attributes["http.target"] == "/actuator/health"'
            - 'attributes["http.route"] == "/actuator/health"'
            - 'attributes["url.path"] == "/actuator/health"'
            - 'attributes["http.target"] == "/actuator/info"'
            - 'attributes["http.route"] == "/actuator/info"'
            - 'attributes["url.path"] == "/actuator/info"'
            - 'attributes["http.target"] == "/actuator/health/liveness"'
            - 'attributes["http.route"] == "/actuator/health/liveness"'
            - 'attributes["url.path"] == "/actuator/health/liveness"'
            - 'attributes["http.target"] == "/actuator/health/readiness"'
            - 'attributes["http.route"] == "/actuator/health/readiness"'
            - 'attributes["url.path"] == "/actuator/health/readiness"'
      resource:
        attributes:
          - key: service.namespace
            value: asset-spy
            action: upsert
          - key: deployment.environment
            value: prod
            action: upsert
      batch: {}
    exporters:
      otlp/jaeger:
        endpoint: jaeger.observability.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [filter/ignore-noisy, resource, batch]
          exporters: [otlp/jaeger]